#!/usr/bin/env python3
"""
Compute sampling-vs-full error for PPL/IFD and draw plots.

Input:
  - per-example full file generated by compute_split_ppl_ifd_full.py

Output:
  - summary CSV
  - PNG figure (2 panels: PPL / IFD)
"""

import argparse
from pathlib import Path

import numpy as np
import pandas as pd


def evaluate_sampling(values: np.ndarray, ratios, repeats: int, seed: int, metric: str) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    baseline = float(values.mean())
    rows = []

    for ratio in ratios:
        n = max(1, int(round(len(values) * ratio)))
        sample_means = []
        abs_errs = []
        rel_errs = []

        for _ in range(repeats):
            idx = rng.choice(len(values), size=n, replace=False)
            sample_mean = float(values[idx].mean())
            sample_means.append(sample_mean)
            abs_err = abs(sample_mean - baseline)
            rel_err = abs_err / abs(baseline) if baseline != 0 else np.nan
            abs_errs.append(abs_err)
            rel_errs.append(rel_err)

        rows.append(
            {
                "metric": metric,
                "ratio": float(ratio),
                "sample_size": int(n),
                "baseline_mean": baseline,
                "sample_mean_avg": float(np.mean(sample_means)),
                "sample_mean_std": float(np.std(sample_means)),
                "abs_error_mean": float(np.mean(abs_errs)),
                "abs_error_p95": float(np.percentile(abs_errs, 95)),
                "rel_error_mean": float(np.nanmean(rel_errs)),
                "rel_error_p95": float(np.nanpercentile(rel_errs, 95)),
            }
        )

    return pd.DataFrame(rows)


def draw_figure(summary_df: pd.DataFrame, output_png: Path):
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, 2, figsize=(14, 5), dpi=150)
    metrics = ["ppl", "ifd"]

    for ax, metric in zip(axes, metrics):
        sub = summary_df[summary_df["metric"] == metric].sort_values("ratio")
        x = sub["ratio"].to_numpy()
        y_mean = sub["rel_error_mean"].to_numpy()
        y_p95 = sub["rel_error_p95"].to_numpy()

        ax.plot(x, y_mean, marker="o", label="rel_error_mean")
        ax.plot(x, y_p95, marker="s", label="rel_error_p95")
        ax.set_title(f"{metric.upper()} Sampling Error vs Full")
        ax.set_xlabel("Sampling Ratio")
        ax.set_ylabel("Relative Error")
        ax.grid(True, alpha=0.3)
        ax.legend()

        for xi, yi, n in zip(x, y_p95, sub["sample_size"].to_numpy()):
            ax.annotate(f"n={n}", (xi, yi), textcoords="offset points", xytext=(0, 6), ha="center", fontsize=8)

    fig.tight_layout()
    fig.savefig(output_png, bbox_inches="tight")
    plt.close(fig)


def parse_ratios(ratio_str: str):
    ratios = []
    for token in ratio_str.split(","):
        token = token.strip()
        if not token:
            continue
        r = float(token)
        if r <= 0 or r > 1:
            raise ValueError(f"ratio must be in (0, 1], got {r}")
        ratios.append(r)
    if not ratios:
        raise ValueError("no valid ratios")
    return sorted(set(ratios))


def main():
    parser = argparse.ArgumentParser(description="Plot sampling error vs full PPL/IFD")
    parser.add_argument("--full_file", required=True, help="Path to split_*_ppl_ifd_full.parquet/csv")
    parser.add_argument("--ratios", default="0.01,0.02,0.05,0.1,0.2,0.3,0.5")
    parser.add_argument("--repeats", type=int, default=200)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--output_dir", required=True)
    parser.add_argument("--prefix", default="sampling_vs_full")
    args = parser.parse_args()

    full_path = Path(args.full_file)
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    ratios = parse_ratios(args.ratios)

    if full_path.suffix == ".parquet":
        df = pd.read_parquet(full_path)
    elif full_path.suffix == ".csv":
        df = pd.read_csv(full_path)
    else:
        raise ValueError("full_file must be .parquet or .csv")

    required_cols = {"ppl", "ifd", "ppl_ok", "ifd_ok"}
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(f"Missing columns in full_file: {missing}")

    ppl_vals = df.loc[df["ppl_ok"] == True, "ppl"].dropna().to_numpy(dtype=np.float64)
    ifd_vals = df.loc[df["ifd_ok"] == True, "ifd"].dropna().to_numpy(dtype=np.float64)
    if len(ppl_vals) == 0 or len(ifd_vals) == 0:
        raise ValueError("No valid ppl/ifd values found")

    ppl_summary = evaluate_sampling(ppl_vals, ratios, args.repeats, args.seed, "ppl")
    ifd_summary = evaluate_sampling(ifd_vals, ratios, args.repeats, args.seed + 1, "ifd")
    summary_df = pd.concat([ppl_summary, ifd_summary], ignore_index=True)

    summary_csv = out_dir / f"{args.prefix}_summary.csv"
    plot_png = out_dir / f"{args.prefix}_plot.png"
    summary_df.to_csv(summary_csv, index=False)
    draw_figure(summary_df, plot_png)

    print(f"Saved summary: {summary_csv}")
    print(f"Saved figure:  {plot_png}")


if __name__ == "__main__":
    main()

