"""
https://github.com/open-compass/opencompass/blob/main/opencompass/datasets/strategyqa.py
"""

import re

# def extract_boolean_answer(text: str, flexible: bool = False) -> str:
#     """
#     Extract boolean answer (True/False) from model output.
    
#     Args:
#         text: Model output text
#         flexible: If True, search entire text if no match in last line
    
#     Returns:
#         str: "True", "False", or "" (empty if not found)
#     """
#     if not text:
#         return ""
    
#     # Normalize
#     text = text.strip()
#     text_upper = text.upper()
    
#     # Direct match: entire text is just "True" or "False"
#     if text_upper == 'TRUE':
#         return "True"
#     if text_upper == 'FALSE':
#         return "False"
    
#     # Single letter T/F
#     if len(text) == 1:
#         if text_upper == 'T':
#             return "True"
#         elif text_upper == 'F':
#             return "False"
    
#     # Multi-line processing: prioritize last non-empty line
#     lines = text.split('\n')
#     search_lines = list(reversed([l.strip() for l in lines if l.strip()]))
    
#     # If strict mode (not flexible), only check last line; if flexible, check all
#     lines_to_check = search_lines if flexible else (search_lines[:1] if search_lines else [])
    
#     for line in lines_to_check:        
#         # Pattern 1: "Answer: True", "The answer is false", "Result: T", "Final Answer: F"
#         match = re.search(r'(?:answer|final answer|result|conclusion|choice|option)[:=\s]+(true|false|t|f)\b', 
#                          line, re.IGNORECASE)
#         if match:
#             ans = match.group(1).upper()
#             return "True" if ans in ['TRUE', 'T'] else "False"
        
#         # Pattern 2: Parentheses or brackets: (True), [False], (T), [F]
#         match = re.search(r'[\(\[\{](true|false|t|f)[\)\]\}]', line, re.IGNORECASE)
#         if match:
#             ans = match.group(1).upper()
#             return "True" if ans in ['TRUE', 'T'] else "False"
        
#         # Pattern 3: Word boundaries (standalone True/False) with optional punctuation
#         # e.g., "True.", "False!", "True" at start/end of line
#         match = re.search(r'(?:^|\s)(true|false)[\.\,\;\!\?]*(?:$|\s)', line, re.IGNORECASE)
#         if match:
#             ans = match.group(1).upper()
#             return "True" if ans == 'TRUE' else "False"
        
#         # Pattern 4: Line starts with True/False followed by separator
#         match = re.search(r'^(true|false)[:=\s)]', line, re.IGNORECASE)
#         if match:
#             ans = match.group(1).upper()
#             return "True" if ans == 'TRUE' else "False"
    
#     # fallback: if no match in last line, return empty
#     return ""

def extract_boolean_answer(text: str) -> str:
    if not text:
        return "N/A"
    match = re.findall(r"(true|false)", text, re.IGNORECASE)
    return match[-1].lower() if match else "N/A"

def strategyqa_pred_postprocess(text: str) -> str:
    text = text.split('\n\n')[0]
    text = text.split('answer is ')[-1]
    match = re.search(r'(yes|no)', text.lower())
    if match:
        return match.group(1)
    return ''

def compute_score(solution_str, ground_truth, method="yes_no", format_score=0.0, score=1.0):
    """
    Evaluate true/false question.
    
    Args:
        solution_str: Text generated by the model.
        ground_truth: Correct answer (can be "True"/"False", "T"/"F", 1/0, "Yes"/"No", etc.)
        method: "flexible" allows searching entire text if no match in last line; 
                "strict" only checks the last substantial line
        format_score: Partial credit (0.0~1.0) for mentioning the correct answer 
                     somewhere in the text (even if extraction failed)
        score: Full score for correct answer (default 1.0)
    
    Returns:
        float: score (1.0 for correct, 0.0 for incorrect, or format_score)
    """

    assert method in ["yes_no", "true_false"]
    
    if not solution_str or ground_truth is None:
        return 0.0
    
    extractor = strategyqa_pred_postprocess if method == "yes_no" else extract_boolean_answer
    
    # Extract prediction
    pred = extractor(solution_str)

    if pred == "true" or pred == "yes":
        pred_bool = True
    elif pred == "false" or pred == "no":
        pred_bool = False
    else:
        return 0.0
    
    # Exact match
    if pred_bool == ground_truth:
        return score
    
    return 0.0

def extract_pred(solution_str: str) -> str:
    return strategyqa_pred_postprocess(solution_str)